// 高タンパク商品データを大量投入するスクリプト
// 使用方法: npx tsx scripts/seed-products.ts

import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const supabase = createClient(supabaseUrl, supabaseKey)

// 商品データ（2024年時点の実際の商品情報をベース）
const products = [
  // ===========================================
  // セブン-イレブン
  // ===========================================
  // サラダチキン系
  {
    store_name: 'seven',
    product_name: 'サラダチキン プレーン',
    price: 238,
    protein: 26.0,
    fat: 1.5,
    carbs: 0.3,
    calories: 114,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'サラダチキン スモーク',
    price: 238,
    protein: 25.0,
    fat: 2.0,
    carbs: 0.5,
    calories: 118,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'サラダチキン ハーブ',
    price: 238,
    protein: 24.5,
    fat: 1.8,
    carbs: 0.8,
    calories: 115,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'サラダチキン 炭火焼',
    price: 248,
    protein: 25.5,
    fat: 2.2,
    carbs: 0.6,
    calories: 122,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'サラダチキンバー プレーン',
    price: 170,
    protein: 14.0,
    fat: 1.0,
    carbs: 0.5,
    calories: 66,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'サラダチキンバー スモーク',
    price: 170,
    protein: 13.5,
    fat: 1.2,
    carbs: 0.8,
    calories: 68,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ほぐしサラダチキン',
    price: 198,
    protein: 21.0,
    fat: 1.5,
    carbs: 0.5,
    calories: 99,
    category: 'サラダチキン',
    is_available: true,
  },
  // たんぱく質が摂れるシリーズ
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる 鶏むね肉のサラダ',
    price: 430,
    protein: 27.5,
    fat: 8.2,
    carbs: 12.3,
    calories: 235,
    category: 'サラダ',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる ローストチキン&スパサラ',
    price: 460,
    protein: 25.0,
    fat: 15.5,
    carbs: 28.0,
    calories: 358,
    category: 'サラダ',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる チキン&エッグサンド',
    price: 398,
    protein: 26.0,
    fat: 14.5,
    carbs: 26.8,
    calories: 345,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる グリルチキン弁当',
    price: 598,
    protein: 32.0,
    fat: 12.0,
    carbs: 58.0,
    calories: 472,
    category: '弁当',
    is_available: true,
  },
  // ゆで卵系
  {
    store_name: 'seven',
    product_name: '味付き半熟ゆでたまご 2個入',
    price: 162,
    protein: 12.8,
    fat: 10.0,
    carbs: 0.6,
    calories: 142,
    category: 'ゆで卵',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '温泉たまご 2個入',
    price: 172,
    protein: 12.0,
    fat: 9.5,
    carbs: 0.8,
    calories: 135,
    category: 'ゆで卵',
    is_available: true,
  },
  // プロテインバー・ドリンク
  {
    store_name: 'seven',
    product_name: 'inバー プロテイン ベイクドチョコ',
    price: 173,
    protein: 16.2,
    fat: 10.6,
    carbs: 12.1,
    calories: 211,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'inバー プロテイン グラノーラ',
    price: 173,
    protein: 15.9,
    fat: 9.5,
    carbs: 14.8,
    calories: 210,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'inバー プロテイン ウェファーバニラ',
    price: 173,
    protein: 10.5,
    fat: 10.2,
    carbs: 14.5,
    calories: 194,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ザバス ミルクプロテイン ココア 200ml',
    price: 152,
    protein: 15.0,
    fat: 0,
    carbs: 10.4,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ザバス ミルクプロテイン バニラ 200ml',
    price: 152,
    protein: 15.0,
    fat: 0,
    carbs: 10.5,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ザバス ミルクプロテイン ストロベリー 200ml',
    price: 152,
    protein: 15.0,
    fat: 0,
    carbs: 10.5,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ザバス ミルクプロテイン 430ml',
    price: 236,
    protein: 15.0,
    fat: 0,
    carbs: 10.0,
    calories: 100,
    category: 'プロテインドリンク',
    is_available: true,
  },
  // その他高タンパク
  {
    store_name: 'seven',
    product_name: 'スモークタン',
    price: 298,
    protein: 16.0,
    fat: 14.5,
    carbs: 1.2,
    calories: 198,
    category: 'おつまみ',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ささみスモーク',
    price: 198,
    protein: 18.0,
    fat: 1.0,
    carbs: 0.5,
    calories: 82,
    category: 'おつまみ',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '豆腐バー 和風だし',
    price: 138,
    protein: 10.5,
    fat: 4.0,
    carbs: 1.5,
    calories: 82,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '豆腐バー 柚子胡椒',
    price: 138,
    protein: 10.0,
    fat: 4.2,
    carbs: 1.8,
    calories: 84,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ギリシャヨーグルト プレーン',
    price: 172,
    protein: 10.2,
    fat: 4.5,
    carbs: 5.0,
    calories: 100,
    category: 'ヨーグルト',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '焼き鮭 切り身',
    price: 248,
    protein: 18.0,
    fat: 8.5,
    carbs: 0.2,
    calories: 149,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'さばの塩焼',
    price: 258,
    protein: 20.5,
    fat: 16.0,
    carbs: 0.3,
    calories: 228,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'ツナ&たまごサンド',
    price: 298,
    protein: 15.5,
    fat: 12.0,
    carbs: 24.5,
    calories: 272,
    category: 'サンドイッチ',
    is_available: true,
  },

  // ===========================================
  // ローソン
  // ===========================================
  // サラダチキン系
  {
    store_name: 'lawson',
    product_name: 'サラダチキン プレーン',
    price: 238,
    protein: 25.5,
    fat: 1.5,
    carbs: 0.4,
    calories: 113,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'サラダチキン ハーブ',
    price: 238,
    protein: 24.5,
    fat: 1.8,
    carbs: 0.8,
    calories: 116,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'サラダチキン スモーク',
    price: 238,
    protein: 24.0,
    fat: 2.0,
    carbs: 0.6,
    calories: 115,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'サラダチキン レモン',
    price: 238,
    protein: 24.2,
    fat: 1.6,
    carbs: 1.0,
    calories: 114,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'サラダチキンスティック プレーン',
    price: 168,
    protein: 13.0,
    fat: 1.0,
    carbs: 0.5,
    calories: 62,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'サラダチキンスティック ブラックペッパー',
    price: 168,
    protein: 12.8,
    fat: 1.2,
    carbs: 0.8,
    calories: 65,
    category: 'サラダチキン',
    is_available: true,
  },
  // たんぱく質シリーズ
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れるチキン&たまごサンド',
    price: 398,
    protein: 26.0,
    fat: 15.2,
    carbs: 28.5,
    calories: 358,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れるチキンのサラダ',
    price: 420,
    protein: 26.5,
    fat: 10.0,
    carbs: 14.0,
    calories: 254,
    category: 'サラダ',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れるパワーサラダ',
    price: 498,
    protein: 28.0,
    fat: 12.5,
    carbs: 18.0,
    calories: 298,
    category: 'サラダ',
    is_available: true,
  },
  // ブランパン（高タンパク・低糖質）
  {
    store_name: 'lawson',
    product_name: 'ブランパン 2個入',
    price: 130,
    protein: 11.4,
    fat: 4.8,
    carbs: 4.4,
    calories: 132,
    category: 'パン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ブランパン チーズ 2個入',
    price: 150,
    protein: 12.8,
    fat: 6.5,
    carbs: 5.2,
    calories: 162,
    category: 'パン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れるブランロール',
    price: 165,
    protein: 13.5,
    fat: 5.0,
    carbs: 6.0,
    calories: 145,
    category: 'パン',
    is_available: true,
  },
  // ゆで卵系
  {
    store_name: 'lawson',
    product_name: '味付たまご 2個入',
    price: 159,
    protein: 12.4,
    fat: 9.8,
    carbs: 0.4,
    calories: 138,
    category: 'ゆで卵',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '半熟煮たまご',
    price: 108,
    protein: 6.2,
    fat: 4.9,
    carbs: 0.2,
    calories: 69,
    category: 'ゆで卵',
    is_available: true,
  },
  // プロテイン系
  {
    store_name: 'lawson',
    product_name: 'ザバス ミルクプロテイン バニラ 200ml',
    price: 183,
    protein: 15.0,
    fat: 0,
    carbs: 10.5,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ザバス ミルクプロテイン ココア 200ml',
    price: 183,
    protein: 15.0,
    fat: 0,
    carbs: 10.4,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'inバー プロテイン ベイクドチョコ',
    price: 180,
    protein: 16.2,
    fat: 10.6,
    carbs: 12.1,
    calories: 211,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'プロテインバー チョコレート',
    price: 180,
    protein: 15.0,
    fat: 8.5,
    carbs: 15.0,
    calories: 198,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '1本満足バー プロテインチョコ',
    price: 151,
    protein: 15.0,
    fat: 9.0,
    carbs: 11.0,
    calories: 185,
    category: 'プロテインバー',
    is_available: true,
  },
  // からあげクン（意外と高タンパク）
  {
    store_name: 'lawson',
    product_name: 'からあげクン レギュラー',
    price: 238,
    protein: 14.0,
    fat: 14.5,
    carbs: 8.0,
    calories: 220,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'からあげクン レッド',
    price: 238,
    protein: 13.5,
    fat: 14.0,
    carbs: 8.5,
    calories: 215,
    category: 'ホットスナック',
    is_available: true,
  },
  // その他
  {
    store_name: 'lawson',
    product_name: 'ほっけの塩焼',
    price: 298,
    protein: 21.0,
    fat: 12.5,
    carbs: 0.2,
    calories: 196,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '銀鮭の塩焼',
    price: 278,
    protein: 19.5,
    fat: 10.0,
    carbs: 0.3,
    calories: 168,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ギリシャヨーグルト パルテノ プレーン',
    price: 178,
    protein: 10.0,
    fat: 4.8,
    carbs: 4.5,
    calories: 100,
    category: 'ヨーグルト',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ギリシャヨーグルト パルテノ ブルーベリー',
    price: 198,
    protein: 9.5,
    fat: 4.5,
    carbs: 10.5,
    calories: 122,
    category: 'ヨーグルト',
    is_available: true,
  },

  // ===========================================
  // ファミリーマート
  // ===========================================
  // グリルチキン系
  {
    store_name: 'familymart',
    product_name: 'グリルチキン プレーン',
    price: 258,
    protein: 27.0,
    fat: 2.5,
    carbs: 0.5,
    calories: 132,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'グリルチキン タンドリー',
    price: 258,
    protein: 26.5,
    fat: 3.0,
    carbs: 1.2,
    calories: 138,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'グリルチキン ブラックペッパー',
    price: 258,
    protein: 26.0,
    fat: 3.2,
    carbs: 0.8,
    calories: 135,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'グリルチキン レモン&ハーブ',
    price: 258,
    protein: 25.5,
    fat: 2.8,
    carbs: 1.5,
    calories: 133,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'サラダチキンバー プレーン',
    price: 168,
    protein: 13.5,
    fat: 1.0,
    carbs: 0.5,
    calories: 64,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'サラダチキンバー スモーク',
    price: 168,
    protein: 13.0,
    fat: 1.2,
    carbs: 0.8,
    calories: 66,
    category: 'サラダチキン',
    is_available: true,
  },
  // RIZAP監修
  {
    store_name: 'familymart',
    product_name: 'RIZAP サラダチキンバー',
    price: 170,
    protein: 14.0,
    fat: 1.5,
    carbs: 1.0,
    calories: 72,
    category: 'サラダチキン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'RIZAP 糖質0麺 汁なし担々麺風',
    price: 298,
    protein: 12.0,
    fat: 8.5,
    carbs: 8.0,
    calories: 158,
    category: '麺',
    is_available: true,
  },
  // たんぱく質シリーズ
  {
    store_name: 'familymart',
    product_name: '全粒粉サンド たんぱく質が摂れるチキン',
    price: 368,
    protein: 24.0,
    fat: 12.0,
    carbs: 32.0,
    calories: 332,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れるチキンサラダ',
    price: 398,
    protein: 25.5,
    fat: 9.5,
    carbs: 12.5,
    calories: 238,
    category: 'サラダ',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れる国産鶏のサラダチキン弁当',
    price: 550,
    protein: 30.0,
    fat: 10.5,
    carbs: 52.0,
    calories: 425,
    category: '弁当',
    is_available: true,
  },
  // ゆで卵系
  {
    store_name: 'familymart',
    product_name: '半熟ゆでたまご 2個入',
    price: 156,
    protein: 12.6,
    fat: 9.6,
    carbs: 0.6,
    calories: 138,
    category: 'ゆで卵',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '味付きゆでたまご',
    price: 86,
    protein: 6.3,
    fat: 4.8,
    carbs: 0.3,
    calories: 69,
    category: 'ゆで卵',
    is_available: true,
  },
  // プロテイン系
  {
    store_name: 'familymart',
    product_name: 'ザバス ミルクプロテイン ココア 200ml',
    price: 183,
    protein: 15.0,
    fat: 0,
    carbs: 10.4,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'ザバス ミルクプロテイン バニラ 200ml',
    price: 183,
    protein: 15.0,
    fat: 0,
    carbs: 10.5,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'inバー プロテイン ベイクドチョコ',
    price: 180,
    protein: 16.2,
    fat: 10.6,
    carbs: 12.1,
    calories: 211,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'inバー プロテイン グラノーラ',
    price: 180,
    protein: 15.9,
    fat: 9.5,
    carbs: 14.8,
    calories: 210,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'プロテインバー ストロベリー',
    price: 178,
    protein: 15.5,
    fat: 8.0,
    carbs: 12.0,
    calories: 182,
    category: 'プロテインバー',
    is_available: true,
  },
  // ホットスナック
  {
    store_name: 'familymart',
    product_name: 'ファミチキ',
    price: 198,
    protein: 12.5,
    fat: 15.0,
    carbs: 14.0,
    calories: 242,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'スパイシーチキン',
    price: 220,
    protein: 13.0,
    fat: 14.5,
    carbs: 13.5,
    calories: 238,
    category: 'ホットスナック',
    is_available: true,
  },
  // その他
  {
    store_name: 'familymart',
    product_name: '焼さば',
    price: 268,
    protein: 19.8,
    fat: 15.5,
    carbs: 0.2,
    calories: 218,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '銀鮭の塩焼き',
    price: 268,
    protein: 18.5,
    fat: 9.8,
    carbs: 0.3,
    calories: 162,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'ギリシャヨーグルト プレーン',
    price: 168,
    protein: 9.8,
    fat: 4.2,
    carbs: 4.8,
    calories: 96,
    category: 'ヨーグルト',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'たんぱく質10g ヨーグルト ストロベリー',
    price: 178,
    protein: 10.0,
    fat: 0,
    carbs: 12.5,
    calories: 90,
    category: 'ヨーグルト',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '豆腐バー',
    price: 128,
    protein: 10.0,
    fat: 3.8,
    carbs: 1.2,
    calories: 78,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'ローストビーフ',
    price: 398,
    protein: 22.0,
    fat: 6.5,
    carbs: 1.0,
    calories: 148,
    category: 'おつまみ',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'スモークささみ',
    price: 188,
    protein: 17.5,
    fat: 1.2,
    carbs: 0.5,
    calories: 82,
    category: 'おつまみ',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'ビーフジャーキー',
    price: 298,
    protein: 16.0,
    fat: 2.5,
    carbs: 8.0,
    calories: 118,
    category: 'おつまみ',
    is_available: true,
  },
]

async function seedProducts() {
  console.log('=== 商品データ投入開始 ===')
  console.log(`投入予定: ${products.length}件`)

  // 既存データを削除
  console.log('既存データを削除中...')
  const { error: deleteError } = await supabase
    .from('products')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000') // 全件削除

  if (deleteError) {
    console.error('削除エラー:', deleteError)
  }

  // 新規データを投入
  console.log('新規データを投入中...')
  const { data, error } = await supabase
    .from('products')
    .insert(products)
    .select()

  if (error) {
    console.error('投入エラー:', error)
    return
  }

  console.log(`✅ ${data?.length || 0}件の商品を投入しました`)

  // 店舗別の集計
  const sevenCount = products.filter(p => p.store_name === 'seven').length
  const lawsonCount = products.filter(p => p.store_name === 'lawson').length
  const familymartCount = products.filter(p => p.store_name === 'familymart').length

  console.log('\n=== 店舗別商品数 ===')
  console.log(`セブン-イレブン: ${sevenCount}件`)
  console.log(`ローソン: ${lawsonCount}件`)
  console.log(`ファミリーマート: ${familymartCount}件`)
}

seedProducts()
