// 商品データ追加スクリプト v2
// 使用方法: npx tsx scripts/seed-products-v2.ts

import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const supabase = createClient(supabaseUrl, supabaseKey)

// 追加商品データ（弁当、おにぎり、麺、パスタ、惣菜など）
const newProducts = [
  // ===========================================
  // セブン-イレブン - 弁当・おにぎり・麺
  // ===========================================
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる チキン&チリビーンズ',
    price: 550,
    protein: 30.2,
    fat: 18.5,
    carbs: 42.0,
    calories: 456,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる 鶏の照り焼き弁当',
    price: 530,
    protein: 28.5,
    fat: 15.0,
    carbs: 55.0,
    calories: 480,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる チキンステーキ弁当',
    price: 580,
    protein: 32.0,
    fat: 16.5,
    carbs: 48.0,
    calories: 470,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '炙り焼チキン弁当',
    price: 498,
    protein: 26.0,
    fat: 14.0,
    carbs: 60.0,
    calories: 475,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'グリルチキン弁当',
    price: 480,
    protein: 24.5,
    fat: 12.0,
    carbs: 58.0,
    calories: 440,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '鮭弁当',
    price: 450,
    protein: 22.0,
    fat: 10.5,
    carbs: 62.0,
    calories: 435,
    category: '弁当',
    is_available: true,
  },
  // おにぎり
  {
    store_name: 'seven',
    product_name: '直巻おむすび 鮭',
    price: 160,
    protein: 5.8,
    fat: 1.5,
    carbs: 38.0,
    calories: 190,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '直巻おむすび ツナマヨネーズ',
    price: 140,
    protein: 5.2,
    fat: 5.0,
    carbs: 35.0,
    calories: 210,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '手巻おにぎり 納豆',
    price: 130,
    protein: 6.5,
    fat: 2.5,
    carbs: 34.0,
    calories: 185,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる 枝豆おにぎり',
    price: 180,
    protein: 8.5,
    fat: 3.0,
    carbs: 32.0,
    calories: 192,
    category: 'おにぎり',
    is_available: true,
  },
  // 麺・パスタ
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる 蒸し鶏のパスタサラダ',
    price: 430,
    protein: 21.5,
    fat: 12.0,
    carbs: 35.0,
    calories: 340,
    category: '麺',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる 冷やし中華',
    price: 498,
    protein: 20.0,
    fat: 8.5,
    carbs: 52.0,
    calories: 368,
    category: '麺',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '蒸し鶏の冷やしそば',
    price: 450,
    protein: 18.0,
    fat: 6.0,
    carbs: 48.0,
    calories: 320,
    category: '麺',
    is_available: true,
  },
  // 惣菜
  {
    store_name: 'seven',
    product_name: 'グリルチキン（黒胡椒）',
    price: 298,
    protein: 20.5,
    fat: 8.0,
    carbs: 2.0,
    calories: 165,
    category: '惣菜',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'グリルチキン（ハーブ）',
    price: 298,
    protein: 19.8,
    fat: 7.5,
    carbs: 2.5,
    calories: 158,
    category: '惣菜',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '砂肝の黒胡椒焼き',
    price: 248,
    protein: 18.0,
    fat: 3.5,
    carbs: 1.0,
    calories: 108,
    category: '惣菜',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'レバニラ炒め',
    price: 298,
    protein: 16.5,
    fat: 12.0,
    carbs: 8.0,
    calories: 210,
    category: '惣菜',
    is_available: true,
  },

  // ===========================================
  // ローソン - 弁当・おにぎり・麺
  // ===========================================
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れる チキンと野菜のスパイスカレー',
    price: 598,
    protein: 27.0,
    fat: 18.0,
    carbs: 58.0,
    calories: 505,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れる グリルチキン弁当',
    price: 530,
    protein: 29.5,
    fat: 14.0,
    carbs: 50.0,
    calories: 445,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '鶏もも肉の照焼弁当',
    price: 498,
    protein: 25.0,
    fat: 16.0,
    carbs: 58.0,
    calories: 480,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'さばの塩焼弁当',
    price: 530,
    protein: 24.0,
    fat: 20.0,
    carbs: 52.0,
    calories: 490,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'から揚弁当',
    price: 498,
    protein: 22.0,
    fat: 24.0,
    carbs: 65.0,
    calories: 565,
    category: '弁当',
    is_available: true,
  },
  // おにぎり
  {
    store_name: 'lawson',
    product_name: '金しゃりおにぎり 焼さけハラミ',
    price: 230,
    protein: 7.5,
    fat: 4.5,
    carbs: 36.0,
    calories: 218,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'おにぎり 紅しゃけ',
    price: 150,
    protein: 5.5,
    fat: 1.8,
    carbs: 37.0,
    calories: 188,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'おにぎり ツナマヨネーズ',
    price: 130,
    protein: 5.0,
    fat: 5.5,
    carbs: 35.0,
    calories: 215,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れるおにぎり 鶏そぼろ',
    price: 180,
    protein: 9.0,
    fat: 3.5,
    carbs: 33.0,
    calories: 202,
    category: 'おにぎり',
    is_available: true,
  },
  // 麺
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れる パスタサラダ',
    price: 420,
    protein: 20.5,
    fat: 10.0,
    carbs: 38.0,
    calories: 330,
    category: '麺',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '蒸し鶏の冷やし中華',
    price: 480,
    protein: 19.0,
    fat: 7.5,
    carbs: 50.0,
    calories: 350,
    category: '麺',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れる 冷製パスタ',
    price: 498,
    protein: 22.0,
    fat: 11.0,
    carbs: 42.0,
    calories: 360,
    category: '麺',
    is_available: true,
  },
  // 惣菜
  {
    store_name: 'lawson',
    product_name: 'からあげクン レギュラー',
    price: 238,
    protein: 14.0,
    fat: 14.0,
    carbs: 8.0,
    calories: 220,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'からあげクン レッド',
    price: 238,
    protein: 13.5,
    fat: 13.5,
    carbs: 9.0,
    calories: 215,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'Lチキ 旨塩',
    price: 200,
    protein: 15.5,
    fat: 11.0,
    carbs: 10.0,
    calories: 205,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ゲンコツメンチ',
    price: 180,
    protein: 8.5,
    fat: 15.0,
    carbs: 12.0,
    calories: 220,
    category: 'ホットスナック',
    is_available: true,
  },

  // ===========================================
  // ファミリーマート - 弁当・おにぎり・麺
  // ===========================================
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れる グリルチキン弁当',
    price: 548,
    protein: 30.0,
    fat: 15.0,
    carbs: 52.0,
    calories: 465,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れる 鶏めし弁当',
    price: 530,
    protein: 28.0,
    fat: 14.5,
    carbs: 55.0,
    calories: 470,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'グリルチキンプレート',
    price: 498,
    protein: 26.5,
    fat: 12.0,
    carbs: 48.0,
    calories: 410,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '炭火焼きとり重',
    price: 480,
    protein: 24.0,
    fat: 13.0,
    carbs: 58.0,
    calories: 450,
    category: '弁当',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '鮭幕の内弁当',
    price: 498,
    protein: 23.0,
    fat: 12.5,
    carbs: 60.0,
    calories: 448,
    category: '弁当',
    is_available: true,
  },
  // おにぎり
  {
    store_name: 'familymart',
    product_name: 'おにぎり 焼しゃけ',
    price: 158,
    protein: 6.0,
    fat: 2.0,
    carbs: 37.0,
    calories: 192,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'おにぎり シーチキンマヨネーズ',
    price: 135,
    protein: 5.0,
    fat: 5.2,
    carbs: 35.0,
    calories: 212,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れる 鶏五目おにぎり',
    price: 175,
    protein: 8.0,
    fat: 3.2,
    carbs: 34.0,
    calories: 200,
    category: 'おにぎり',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'スーパー大麦 枝豆とひじきおにぎり',
    price: 160,
    protein: 5.5,
    fat: 2.0,
    carbs: 32.0,
    calories: 170,
    category: 'おにぎり',
    is_available: true,
  },
  // 麺
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れる チキンと野菜のパスタサラダ',
    price: 430,
    protein: 21.0,
    fat: 11.5,
    carbs: 36.0,
    calories: 335,
    category: '麺',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'サラダチキンの冷やし中華',
    price: 498,
    protein: 19.5,
    fat: 8.0,
    carbs: 52.0,
    calories: 362,
    category: '麺',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '蒸し鶏のざるそば',
    price: 430,
    protein: 17.5,
    fat: 5.5,
    carbs: 50.0,
    calories: 325,
    category: '麺',
    is_available: true,
  },
  // ホットスナック
  {
    store_name: 'familymart',
    product_name: 'ファミチキ',
    price: 198,
    protein: 12.5,
    fat: 15.5,
    carbs: 14.0,
    calories: 252,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'スパイシーチキン',
    price: 198,
    protein: 13.0,
    fat: 14.0,
    carbs: 12.0,
    calories: 230,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'ささみ揚げ',
    price: 150,
    protein: 15.0,
    fat: 5.0,
    carbs: 8.0,
    calories: 140,
    category: 'ホットスナック',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'チーズインハンバーグ',
    price: 230,
    protein: 12.0,
    fat: 16.0,
    carbs: 10.0,
    calories: 235,
    category: 'ホットスナック',
    is_available: true,
  },

  // ===========================================
  // 追加: プロテイン系ドリンク・バー
  // ===========================================
  // セブン
  {
    store_name: 'seven',
    product_name: 'SAVAS ミルクプロテイン バニラ風味',
    price: 178,
    protein: 15.0,
    fat: 0.0,
    carbs: 10.0,
    calories: 100,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'SAVAS ミルクプロテイン ストロベリー',
    price: 178,
    protein: 15.0,
    fat: 0.0,
    carbs: 10.5,
    calories: 102,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'inゼリー プロテイン',
    price: 230,
    protein: 10.0,
    fat: 0.0,
    carbs: 20.0,
    calories: 120,
    category: 'プロテインドリンク',
    is_available: true,
  },
  // ローソン
  {
    store_name: 'lawson',
    product_name: 'SAVAS ミルクプロテイン ココア風味',
    price: 178,
    protein: 15.0,
    fat: 0.0,
    carbs: 10.2,
    calories: 101,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'タンパクトヨーグルト ブルーベリー',
    price: 178,
    protein: 12.0,
    fat: 0.0,
    carbs: 12.0,
    calories: 96,
    category: 'ヨーグルト',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'タンパクトヨーグルト プレーン',
    price: 168,
    protein: 12.5,
    fat: 0.0,
    carbs: 8.0,
    calories: 82,
    category: 'ヨーグルト',
    is_available: true,
  },
  // ファミマ
  {
    store_name: 'familymart',
    product_name: 'SAVAS ミルクプロテイン バナナ風味',
    price: 178,
    protein: 15.0,
    fat: 0.0,
    carbs: 10.8,
    calories: 103,
    category: 'プロテインドリンク',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'プロテインバー チョコレート',
    price: 180,
    protein: 15.5,
    fat: 8.0,
    carbs: 12.0,
    calories: 185,
    category: 'プロテインバー',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'プロテインバー ストロベリー',
    price: 180,
    protein: 15.0,
    fat: 7.5,
    carbs: 13.0,
    calories: 180,
    category: 'プロテインバー',
    is_available: true,
  },

  // ===========================================
  // 追加: 低脂質・ヘルシー系
  // ===========================================
  {
    store_name: 'seven',
    product_name: '豆腐そうめん風',
    price: 298,
    protein: 8.0,
    fat: 3.5,
    carbs: 6.0,
    calories: 88,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: '蒸し大豆',
    price: 128,
    protein: 12.5,
    fat: 6.0,
    carbs: 5.0,
    calories: 125,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '国産大豆の絹とうふ',
    price: 98,
    protein: 7.0,
    fat: 4.0,
    carbs: 2.0,
    calories: 72,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '蒸し黒豆',
    price: 138,
    protein: 11.0,
    fat: 5.5,
    carbs: 8.0,
    calories: 128,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '絹ごし豆腐',
    price: 88,
    protein: 6.5,
    fat: 3.5,
    carbs: 2.5,
    calories: 68,
    category: '豆腐',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '枝豆（冷凍）',
    price: 198,
    protein: 11.5,
    fat: 6.0,
    carbs: 5.0,
    calories: 120,
    category: 'おつまみ',
    is_available: true,
  },

  // ===========================================
  // 追加: 魚系
  // ===========================================
  {
    store_name: 'seven',
    product_name: '銀鮭の塩焼',
    price: 298,
    protein: 18.0,
    fat: 12.0,
    carbs: 0.5,
    calories: 182,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'さばの味噌煮',
    price: 298,
    protein: 16.0,
    fat: 15.0,
    carbs: 8.0,
    calories: 235,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: '焼鮭切り身',
    price: 280,
    protein: 17.5,
    fat: 11.0,
    carbs: 0.5,
    calories: 172,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'さばの塩焼',
    price: 268,
    protein: 17.0,
    fat: 14.0,
    carbs: 0.3,
    calories: 195,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '紅鮭の塩焼',
    price: 298,
    protein: 18.5,
    fat: 10.5,
    carbs: 0.5,
    calories: 170,
    category: '魚',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'さば味噌煮',
    price: 280,
    protein: 15.5,
    fat: 14.5,
    carbs: 7.5,
    calories: 225,
    category: '魚',
    is_available: true,
  },

  // ===========================================
  // 追加: サンドイッチ・パン
  // ===========================================
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる チキン&たまごサンド',
    price: 350,
    protein: 22.0,
    fat: 14.0,
    carbs: 25.0,
    calories: 315,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'seven',
    product_name: 'たまごサンド',
    price: 270,
    protein: 10.5,
    fat: 15.0,
    carbs: 22.0,
    calories: 268,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れる ローストチキンサンド',
    price: 380,
    protein: 23.5,
    fat: 12.0,
    carbs: 26.0,
    calories: 305,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ハムたまごサンド',
    price: 298,
    protein: 12.0,
    fat: 13.0,
    carbs: 24.0,
    calories: 262,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'たんぱく質が摂れる グリルチキンサンド',
    price: 368,
    protein: 24.0,
    fat: 11.5,
    carbs: 24.0,
    calories: 298,
    category: 'サンドイッチ',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: 'ツナたまごサンド',
    price: 280,
    protein: 11.0,
    fat: 14.5,
    carbs: 23.0,
    calories: 270,
    category: 'サンドイッチ',
    is_available: true,
  },
  // パン
  {
    store_name: 'seven',
    product_name: 'たんぱく質が摂れる チキン＆チーズロール',
    price: 298,
    protein: 18.0,
    fat: 12.0,
    carbs: 28.0,
    calories: 295,
    category: 'パン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'ブランパン 2個入',
    price: 130,
    protein: 5.5,
    fat: 2.5,
    carbs: 4.5,
    calories: 65,
    category: 'パン',
    is_available: true,
  },
  {
    store_name: 'lawson',
    product_name: 'たんぱく質が摂れる ツナチーズパン',
    price: 280,
    protein: 16.0,
    fat: 14.0,
    carbs: 22.0,
    calories: 280,
    category: 'パン',
    is_available: true,
  },
  {
    store_name: 'familymart',
    product_name: '全粒粉サンド ツナ&たまご',
    price: 268,
    protein: 12.5,
    fat: 13.0,
    carbs: 26.0,
    calories: 275,
    category: 'パン',
    is_available: true,
  },
]

async function seedProducts() {
  console.log('Adding new products...')
  console.log(`Total products to add: ${newProducts.length}`)

  const { data, error } = await supabase
    .from('products')
    .insert(newProducts)
    .select()

  if (error) {
    console.error('Error inserting products:', error)
    return
  }

  console.log(`Successfully added/updated ${data?.length || 0} products`)

  // カテゴリ別集計
  const { data: allProducts } = await supabase
    .from('products')
    .select('category')
    .eq('is_available', true)

  if (allProducts) {
    const categoryCounts: Record<string, number> = {}
    allProducts.forEach(p => {
      categoryCounts[p.category] = (categoryCounts[p.category] || 0) + 1
    })
    console.log('\nCategory breakdown:')
    Object.entries(categoryCounts)
      .sort((a, b) => b[1] - a[1])
      .forEach(([cat, count]) => {
        console.log(`  ${cat}: ${count}`)
      })
    console.log(`\nTotal products: ${allProducts.length}`)
  }
}

seedProducts()
